import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
// const sidebars: SidebarsConfig = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    "intro",
    "installation",
    "quick-start",
    {
      type: "category",
      label: "Producer",
      items: [
        "producer/basic-usage",
        "producer/delivery-result",
        "producer/custom-keys",
        "producer/headers",
        "producer/configuration",
        "producer/middleware",
      ],
    },
    {
      type: "category",
      label: "Consumer",
      items: [
        "consumer/basic-usage",
        "consumer/configuration",
        "consumer/acknowledgment",
        "consumer/metadata",
        "consumer/middleware",
      ],
    },
    {
      type: "category",
      label: "Serialization",
      items: ["serialization/default", "serialization/custom"],
    },
    {
      type: "category",
      label: "Advanced",
      items: [
        "advanced/configuration-sections",
        "advanced/multiple-assemblies",
      ],
    },
    "api-reference",
  ],
};

export default sidebars;
